HarvestImport.allZoneLocalizations = {
	["en"] = {
		["alikr"]        = "Alik'r Desert",
		["auridon"]      = "Auridon, Khenarthi's Roost",
		["bangkorai"]    = "Bangkorai",
		["coldharbor"]   = "Coldharbour",
		["craglorn"]     = "Craglorn",
		["cyrodiil"]     = "Cyrodiil",
		["deshaan"]      = "Deshaan",
		["eastmarch"]    = "Eastmarch",
		["glenumbra"]    = "Glenumbra, Betnikh, Stros M'Kai",
		["grahtwood"]    = "Grahtwood",
		["greenshade"]   = "Greenshade",
		["malabaltor"]   = "Malabal Tor",
		["reapersmarch"] = "Reaper's March",
		["rivenspire"]   = "Rivenspire",
		["shadowfen"]    = "Shadowfen",
		["stonefalls"]   = "Stonefalls, Bal Foyen, Bleakrock Isle",
		["stormhaven"]   = "Stormhaven",
		["therift"]      = "The Rift",
		["wrothgar"]      = "Wrothgar",
		["thievesguild"] = "Hew's Bane",
		["darkbrotherhood"] = "Gold Coast",
	},
	["de"] = {
		["alikr"]        = "Alik'r-WÃ¼ste",
		["auridon"]      = "Auridon, Khenarthis Rast",
		["bangkorai"]    = "Bangkorai",
		["coldharbor"]   = "Kalthafen",
		["craglorn"]     = "Craglorn",
		["cyrodiil"]     = "Cyrodiil",
		["deshaan"]      = "Deshaan",
		["eastmarch"]    = "Ostmarschen",
		["glenumbra"]    = "Glenumbra, Betnikh, Stros M'Kai",
		["grahtwood"]    = "Grahtwald",
		["greenshade"]   = "GrÃ¼nschatten",
		["malabaltor"]   = "Malabal Tor",
		["reapersmarch"] = "Schnittermark",
		["rivenspire"]   = "Kluftspitze",
		["shadowfen"]    = "Schattenfenn",
		["stonefalls"]   = "SteinfÃ¤lle, Bal Foyen, Ã–dfels",
		["stormhaven"]   = "Sturmhafen",
		["therift"]      = "Rift",
	},
	["fr"] = {
		["alikr"]        = "dÃ©sert d'Alik'r",
		["auridon"]      = "Auridon, perchoir de Khenarthi",
		["bangkorai"]    = "Bangkorai",
		["coldharbor"]   = "Havreglace",
		["craglorn"]     = "Craglorn",
		["cyrodiil"]     = "Cyrodiil",
		["deshaan"]      = "Deshaan",
		["eastmarch"]    = "Estemarche",
		["glenumbra"]    = "Glenumbra, Betnikh, Stros M'Kai",
		["grahtwood"]    = "bois de Graht",
		["greenshade"]   = "Prasin",
		["malabaltor"]   = "Malabal Tor",
		["reapersmarch"] = "marche de la Camarde",
		["rivenspire"]   = "Fendretour",
		["shadowfen"]    = "Fangeombre",
		["stonefalls"]   = "Ã‰boulis, Bal Foyen, Ã®le de Morneroc",
		["stormhaven"]   = "Havre-tempÃªte",
		["therift"]      = "BrÃ¨che",
	},
}

HarvestImport.zoneLocalization = (HarvestImport.allZoneLocalizations[Harvest.language]) or (HarvestImport.allZoneLocalizations["en"])

function HarvestImport.GetLocalizedZone( zone )
    return (HarvestImport.zoneLocalization[ zone ] or HarvestImport.allZoneLocalizations["en"][ zone ]) or zone
end

